project:
  type: website

website:
  title: "Text Preprocessing Effects on Fake News Detection"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Binary Response.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

